### ISSUE TITLE
Thesis link broken

### ISSUE THREAD

**Issue by hellow554** [Nilix007/betree_storage_stack#1]
The link (https://wr.informatik.uni-hamburg.de/_media/research:theses:felix_wiedemann_modern_storage_stack_with_key_value_store_interface_and_snapshots_based_on_copy_on_write_b%CE%B5_trees.pdf) shows not found

**Comment by Nilix007** [comment]
@michaelkuhn Please have look :)

Link is broken here as well: https://wr.informatik.uni-hamburg.de/research/theses#section2018

**Comment by michaelkuhn** [comment]
That's what you get for using Unicode in your title. :wink:
The link should work now. (By the way: `README.md` still contains an outdated link.)

**Comment by hellow554** [comment]
ping @Nilix007, please update the Readme and close this issue
